### ISSUE TITLE
Compilation errors in eclipse

### ISSUE THREAD

**Issue by Processmodifyer** [Arenovas/Minecraft-Indev-Mappings#1]
i want to create mods in indev, but 150 compilation errors.
please fix code, some code is obfucasted

**Comment by Arenovas** [comment]
If you used the exact Engima version and Indev version, then patched the sources with the included patch file, it should have gotten it fully patched and working. Aside from maybe like 1 or 2 simple errors from what I've seen.

**Comment by Processmodifyer** [comment]
ok

**Comment by Processmodifyer** [comment]
tell me

**Comment by Processmodifyer** [comment]
fixed, thanks
