### ISSUE TITLE
Any Plans for Minecraft infdev

### ISSUE THREAD

**Issue by Processmodifyer** [Arenovas/Minecraft-Indev-Mappings#3]
any mappings for Minecraft infdev in some month or near future?

**Comment by Arenovas** [comment]
Not at the moment from me, but I do believe someone else was doing such. Also, if you have any questions about this kind of stuff, do please refrain from asking here and ask them on the Modification Station Discord found here if you're not already in it. https://discord.gg/8Qky5XY

**Comment by Processmodifyer** [comment]
that sad, my discord has problems and errors, please don't become mad to me, i love github

**Comment by Arenovas** [comment]
It shouldn't be too difficult to fix whatever problems you have with Discord. And I won't be mad.

**Comment by Processmodifyer** [comment]
ok
