### ISSUE TITLE
Gamemode classes are mislabeled

### ISSUE THREAD

**Issue by TolerableDruid6** [Arenovas/Minecraft-Indev-Mappings#4]
PlayerControllerMP and PlayerControllerSP are actually Creative and Survival gamemode classes, respectively. Minecraft had no seperate internal "multiplayer" mode until Alpha. These should probably be renamed in order to prevent confusion.

**Comment by Arenovas** [comment]
Just fixed in a newer version, will probably push once I've developed a new and hopefully better patch file.

**Comment by TolerableDruid6** [comment]
Good to hear!

**Comment by TolerableDruid6** [comment]
Also likewise, I believe the "multiplayerWorld" in the World class is also similarly mislabelled, and is related to Creative also.

**Comment by Arenovas** [comment]
Finally pushed the new patch file and mappings, fixing the incorrect PlayerController names and renaming multiplayerWorld to survivalWorld.
